language: node_js
node_js:
  - "9.9"
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - dpkg --compare-versions `npm -v` ge 6.0 || npm i -g npm@^6.0
install:
  - npm install
scripts:
  - npm run lint
  - npm test