language: node_js
node_js:
  - '12.16'
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - echo "engine-strict=true" >> .npmrc
install:
  - travis_wait 30 npm install
script:
  - npm run eslint
  - npm run prettier:ci
  - npm test
